/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gtercn_recognizer_plate_PlateRecognizer */

#ifndef _Included_com_airwen_recognizer_plate_PlateRecognizer
#define _Included_com_airwen_recognizer_plate_PlateRecognizer
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jstring JNICALL Java_com_airwen_recognizer_plate_PlateRecognizer_stringFromJNI(JNIEnv *, jclass);
//JNIEXPORT jlong JNICALL Java_com_airwen_recognizer_plate_PlateRecognizer_initPR(JNIEnv *, jclass, jstring, jstring);
//JNIEXPORT jlong JNICALL Java_com_airwen_recognizer_plate_PlateRecognizer_uninitPR(JNIEnv *, jclass, jlong);
JNIEXPORT jbyteArray JNICALL Java_com_airwen_recognizer_plate_PlateRecognizer_plateRecognize(JNIEnv *, jclass,jstring);

#ifdef __cplusplus
}
#endif
#endif
